version: '3'

services:
  web:
    image: nginx:1.23.1
    ports:
        - "8080:80"
        - "80:80"
    volumes:
        - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./app:/app

  php:
    build:
      context: ./php
      dockerfile: PHP.Dockerfile
    image: php:fpm
    expose:
      - 9000
    volumes:
      - ./app:/app
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      
  mysql:
      image: mariadb:10.9.2
      environment:
          MYSQL_ROOT_PASSWORD: 'secret'
          MYSQL_USER: 'tutorial'
          MYSQL_PASSWORD: 'secret'
          MYSQL_DATABASE: 'tutorial'
      volumes:
          - mysqldata:/var/lib/mysql
      ports:
          - 3306:3306
volumes:
    mysqldata: {}